# Problem Description

This data set consists of three types of entities: (a) the 
specification of an auto in terms of various characteristics, (b) 
its assigned insurance risk rating, (c) its normalized losses in use 
as compared to other cars.  The second rating corresponds to the 
degree to which the auto is more risky than its price indicates. 
Cars are initially assigned a risk factor symbol associated with its 
price.   Then, if it is more risky (or less), this symbol is 
adjusted by moving it up (or down) the scale.  Actuarians call this 
process "symboling".  A value of +3 indicates that the auto is 
risky, -3 that it is probably pretty safe.  

```{r risk-scale, echo=FALSE}
plot.new()
plot.window(c(-3,3), c(-1, 1))

axis(1, at=-3:3, pos=0)

lines(c(0.5, 0.5, 3, 3), c(0.1, 0.2, 0.2, 0.1), col="red")
text(1.75, 0.3, 'Risky' )  # the plotrix package has a function for text in a box 

lines(c(-3, -3, -0.5, -0.5), c(0.1, 0.2, 0.2, 0.1), col="green")
text(-1.75, 0.3, 'Safe')
```

The third factor is the relative average loss payment per insured 
vehicle year.  This value is normalized for all autos within a 
particular size classification (two-door small, station wagons, 
sports/speciality, etc...), and represents the average loss per car 
per year.
