# Future Analysis

As with any data analysis, the quality of the input data will determine the quality of the resulting models. In this case we started with 26 factors. A good way to increase the quality of the model would be to provide it with more factors and potentially more levels within the factors. This would be a good investment in time as it would strengthen the models created with that data.

All of this data also is only related to the automobeile itself, and does not account for the individual driving it. Known things like distracted driving that that have nothing to do with the automobeile safety itself, but do add to the risk of an insurer would be useful to look into. To do this however would require a lot more data and analysis. Some technologies however that distract car drivers, could be leveraged to make the car itself.Technology and in partucular the increase of telematics within vehicles and internet of things (IoT) connected devices, will increase the ubiquity and variety of this datastream. With the advances in autonomous vehicles, behavorial factors may impact results less, but is something to monitor for the future of auto risk classification.
